### PR TITLE
Replace type=text with type=number for 4 digit code input

### PR DESCRIPTION
**Pull request by simonaszilinskas**
**Key Changes:**

- Input fields for the verification code are now of type number instead of text.
- This change triggers a numeric keypad on smartphones, facilitating easier and more accurate entry of the verification code.

**Benefits:**

- Enhanced User Experience: Users on mobile devices will now be presented with a numeric keypad, which is more intuitive and less error-prone for entering numerical codes.
- Streamlined Data Entry: This change simplifies the input process, especially on smaller screens, by reducing the need to switch between different keyboard layouts.
- Consistency and Accuracy: Ensures that users input numbers, as intended for verification codes, avoiding potential issues with text input.

### CODE REVIEW

**Review by Quentinchampenois — CHANGES_REQUESTED** [review]
Hello @simonaszilinskas,

I tested it locally and it does not seems to be working, see screenshot when I enter a valid confirmation code 

Screenshot 2024-01-29 at 16 09 17

Flash message is empty and it is not considered as valid

Also, I noticed that you can't copy / paste on Desktop with the input type `number`, is this the expected behaviour ?

**Comment by Quentinchampenois** [comment]
About the failing workflow on the CI this is not related to the modifications, we will fix it before merge

**Comment by simonaszilinskas** [comment]
> Hello @simonaszilinskas,
> 
> I tested it locally and it does not seems to be working, see screenshot when I enter a valid confirmation code
> 
> Screenshot 2024-01-29 at 16 09 17
> Flash message is empty and it is not considered as valid
> 
> Also, I noticed that you can't copy / paste on Desktop with the input type `number`, is this the expected behaviour ?

Thank you for the review Quentin. Indeed, it was breaking because of a confusion in the commit I did. I did a new commit that instead of changing the type of the input, adds a rule that should trigger smartphones for a specific numeric keyboard and that doesn't hinder the functionnality.

**Review by Quentinchampenois — APPROVED** [review]
Nice it works as expected, I will commit to fix the CI !

**Pull request merged**
